language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"

env:
  - GO111MODULE=on

install:
  - mkdir -p $HOME/gopath/src/github.com/gemnasium/logrus-graylog-hook/v3
  - mv $HOME/gopath/src/github.com/gemnasium/logrus-graylog-hook $HOME/gopath/src/github.com/gemnasium/logrus-graylog-hook/v3
  - cd $HOME/gopath/src/github.com/gemnasium/logrus-graylog-hook/v3

script:
  - env GO111MODULE=on go test -v ./...